### ISSUE TITLE
MatterBridge Support

### ISSUE THREAD

**Issue by ljlongwing** [spantaleev/matrix-docker-ansible-deploy#2142] opened 2022-09-29 20:49 UTC
I recently joined a 'Mattermost' chat group and I've consolidated all of my chat into Matrix...I see that there is an existing bridge

https://matrix.org/docs/projects/bot/matterbridge

But looking in this playbook, I don't see that bridge.

I have no clue what would be needed to add an existing bridge to this playbook....I assume that it's possible considering the number of bridges already in here, but wouldn't have the slightest clue how to go about doing it.

Anyone with knowledge on how to do it, or teach me how, I'm game

**Comment by ljlongwing** [comment] 2022-10-17 18:48
anyone?

**Comment by rltas** [comment] 2023-03-17 12:06
This is a duplicate of #1458.

**Closed** 2023-03-17 12:41 UTC
