### ISSUE TITLE
How to use custom subdomains?

### ISSUE THREAD

**Issue by JohannesFleischer** [spantaleev/matrix-docker-ansible-deploy#2574] opened 2023-03-16 16:37 UTC
Hi,

I would like to use a "chat" subdomain instead of the default "matrix"/"element" domain for my server. 
This would allow me to switch to another server at some point later without having to change all references to the matrix.url.tld or element.url.tld address of the server.

I know that this could also be implemented using a redirect, but I would like to define this directly when setting up the server, but unfortunately I have not found the settings where this is defined.
Doing the normal installation and replacing matrix.url.tld with chat.url.tld resulted in a 404 when calling the page.

**Comment by aaronraimist** [comment] 2023-03-16 19:07
Set `matrix_server_fqn_matrix` and `matrix_server_fqn_element` to the domains you want to use in your `vars.yml`. For example `matrix_server_fqn_matrix: "chat.{{ matrix_domain }}"`. Setting both to the same subdomain is not a good idea from a security perspective.

For what it's worth, matrix is already a generic term. The server software you would be using would be Synapse, Dendrite, or Conduit.

**Comment by rltas** [comment] 2023-03-17 13:07
This probably won't work without further modications anyway because 
`traefik.http.routers.matrix-client-element.rule` and `traefik.http.routers.matrix-nginx-proxy-matrix-client.rule` would be the same; path/prefix matching and redirect are currently still handled by nginx-proxy after those rules are evaluated.

**Comment by aaronraimist** [comment] 2023-03-18 03:32
@JohannesFleischer if the problem is solved you can close the issue

**Closed** 2023-03-18 10:49 UTC
Labels: question, outdated
