### ISSUE TITLE
Add support for self-hosting Unified Push

### ISSUE THREAD

**Issue by Cadair** [spantaleev/matrix-docker-ansible-deploy#1460] opened 2021-12-14 11:19 UTC
Both Fluffychat and SchildiChat now support using [Unified Push](https://unifiedpush.org/) as an alternative way of getting push notifications.

The cool thing about UP is that it allows you to choose from a selection of push transports, such as Gotify, FCM or direct push and some of these are self-hostable.

From discussions in #unifiedpush:matrix.org it seems the best stack to self host would be the Gotify server and [common-proxies](https://github.com/UnifiedPush/common-proxies) and hook that into nginx.

**Comment by HarHarLinks** [comment] 2021-12-27 19:01
From my research, I agree with the suggested approach of gotify + common-proxies.
They offer a pre-made nginx config for this: https://github.com/UnifiedPush/common-proxies/blob/main/docs/reverse_proxy.md#nginx

**Comment by HarHarLinks** [comment] 2022-04-08 13:57
I am hearing that gotify-up is currently looking for a maintainer.
There is https://ntfy.sh/ as an alternative.

One key difference is that gotify (for now) requires you to register each user that wants to use it, while ntfy on the other hand is public by design. While easier setup is in everyone's interest, hosting a public instance might not.

I have heard users report on https://matrix.to/#/#android:schildi.chat that the ntfy android client might use less battery.

**Comment by HarHarLinks** [comment] 2022-07-05 07:36
@spantaleev @julianfoad is this ticket resolved as of e4cbdd5? Which features are missing (presumably auth?)

**Comment by julianfoad** [comment] 2022-07-05 08:00
I would consider this resolved by the addition of ntfy server.

Auth is the one enhancement that I have heard requested. I don't have a clear idea what's the best way to do that, nor how important it is, so no concrete plans for that.

**Closed** 2022-07-05 16:45 UTC
