### ISSUE TITLE
Email addresses/phone numbers do not show up in the Settings tab

### ISSUE THREAD

**Issue by schopenhauer** [spantaleev/matrix-docker-ansible-deploy#503] opened 2020-05-14 20:15 UTC
The issue has already been reported in the following [bug report](https://github.com/vector-im/riot-web/issues/13033#) logged in the `riot-web` repo.

Potential solution would be to add the ACAO directive to the reverse proxy - to be tested.

```
add_header Access-Control-Allow-Origin *;
```

**Comment by ns130291** [comment] 2020-05-17 16:49
Adding the header in the reverse proxy (in my case haproxy) solves the CORS error in the browser but doesn't help with the `405 Method Not Allowed` error. 
I guess the header isn't set when this error occurs as all other responses from the identity module have `Access-Control-Allow-Origin: *` set.

**Comment by t2d** [comment] 2020-05-18 17:47
running with `-t self-check` doesn't report any problems but this issue persists

**Comment by 0x46616c6b** [comment] 2020-05-19 15:14
Maybe that is related to #511. If `ma1sd` not configured with enabled `v2` api prefix Riot reports a problem with CORS (405 Method not allowed).

**Comment by ns130291** [comment] 2020-05-19 20:53
with the new change I'm no longer getting the 405 error, but now it says `401 Unauthorized`

**Comment by rootuser** [comment] 2020-05-28 09:42
I can confirm that the actual release fixes the CORS header problem.
Alas I have issues with ma1sd instead; 

The identity server is requested for 3PIDs, but fails with the followin error (from the Javascript console:)

> Unable to reach identity server at https://matrix.myserver.de to check for 3PIDs bindings in Settings
> Error: Unsupported identity server: bad response

Do you think that would be fixed in the new ma1sd release with v2 enabled?

**Comment by spantaleev** [comment] 2020-05-28 13:18
You can try the ma1sd RC by putting this in your `vars.yml` file:

```yaml
matrix_ma1sd_docker_image: "ma1uta/ma1sd:2.4.0-rc1"
```

Let us know if it helps! If not, you can report the issue at the [ma1sd](https://github.com/ma1uta/ma1sd) repository.

**Comment by rootuser** [comment] 2020-05-28 14:01
Thanks for your reply!

I did try it but, alas, to no avail. I will report the bug.

**Comment by spantaleev** [comment] 2020-06-09 05:32
Bug seems to be reported here: https://github.com/ma1uta/ma1sd/issues/48

**Comment by jmastr** [comment] 2020-07-09 07:12
@spantaleev ma1sd v2.4.0 is now released, but the bug is still present. I can confirm this error:
```
Unable to reach identity server at https://matrix.trust2core.rocks to check for 3PIDs bindings in Settings
```

On a side note: if I switch from my Identity Server to https://vector.im, it gives me an error saying that it cannot delete the data on my Identity Server because it is not reachable.

**Comment by jmastr** [comment] 2020-07-09 07:47
For me solution was to add this to ma1sd config:
```
hashing:
  enabled: true # enable or disable the hash lookup MSC2140 (default is false)
  pepperLength: 20 # length of the pepper value (default is 20)
  rotationPolicy: per_requests # or `per_seconds` how often the hashes will be updating
  hashStorageType: sql # or `in_memory` where the hashes will be stored
  algorithms:
    - none   # the same as v1 bulk lookup
    - sha256 # hash the 3PID and pepper.
  delay: 2m # how often hashes will be updated if rotation policy = per_seconds (default is 10s)
  requests: 10 # how many lookup requests will be performed before updating hashes if rotation policy = per_requests (default is 10)
```
https://github.com/ma1uta/ma1sd/blob/master/docs/MSC2140_MSC2134.md#hash-lookup

**Comment by jmastr** [comment] 2020-07-10 14:42
I did a fresh install and the error still persists. It reports unauthorised, but the real problem is however this:
```
Jul 10 14:38:22 matrix matrix-ma1sd[5460]: [XNIO-1 task-7] INFO io.kamax.mxisd.auth.AccountManager - Domain resolved: trust2core.com => https://matrix.trust2core.com:8448
Jul 10 14:38:22 matrix matrix-ma1sd[5460]: [XNIO-1 task-7] ERROR io.kamax.mxisd.auth.AccountManager - Unable to get user info.
Jul 10 14:38:22 matrix matrix-ma1sd[5460]: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <matrix.trust2core.com> doesn't match any of the subject alternative names: [trust2core.com]
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:507)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:437)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at io.kamax.mxisd.auth.AccountManager.getUserId(AccountManager.java:77)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at io.kamax.mxisd.auth.AccountManager.register(AccountManager.java:53)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at io.kamax.mxisd.http.undertow.handler.auth.v2.AccountRegisterHandler.handleRequest(AccountRegisterHandler.java:54)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at io.kamax.mxisd.http.undertow.handler.SaneHandler.handleRequest(SaneHandler.java:71)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Jul 10 14:38:22 matrix matrix-ma1sd[5460]:         at java.lang.Thread.run(Thread.java:748)
```

The certificates afaik are properly handled by let's encrypt, so I don't know, what is going on here.

**Comment by jmastr** [comment] 2020-07-15 11:31
Please see: https://github.com/ma1uta/ma1sd/issues/48#issuecomment-658714999

**Closed** 2020-07-30 06:31 UTC
