### ISSUE TITLE
Matrix-Signal bridge fails to upload media

### ISSUE THREAD

**Issue by whowantsmybigdata** [spantaleev/matrix-docker-ansible-deploy#3656] opened 2024-10-21 18:20 UTC
As described [here](https://github.com/mautrix/signal/issues/564), 
the bridge in v0.7.2 has a bug when uploading media. 

Error message:
`Uploading images shows error — Your message was not bridged: failed to reupload media: `

It's solved by using the latest docker version so setting:

`matrix_mautrix_signal_version: latest`

in

[`roles/custom/matrix-bridge-mautrix-signal/defaults/main.yml`](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/c5e6873e4b6dedc3ca4621ae98ac15979b1e6f25/roles/custom/matrix-bridge-mautrix-signal/defaults/main.yml#L12)

**Comment by syne909** [comment] 2024-10-22 02:22
Same issue. Needs to be merged.

**Comment by Zepmann** [comment] 2024-10-25 11:18
Confirmed. Note that the workaround noted by @whowantsmybigdata can be applied to your playbook configuration instead. It is not necessary to edit source files you get from upstream.

**Comment by TheCraiggers** [comment] 2024-12-01 01:10
0.7.3 has been released by upstream, I think we just need the yaml file updated to point to the newest version?

Is this the sort of thing a PR would be welcome for? Doesn't seem like it would be. Also, I see bots updating the other plugin versions. I wonder why Signal isn't updated this way as well.

**Comment by spantaleev** [comment] 2024-12-01 06:57
The playbook has been on 0.7.3 since dd23e2d1c9b46dfcbd8805c0af5f8fba61bce36d (2 weeks ago).

It should fix this issue, but let me know if it doesn't and we can re-open it.

**Closed by spantaleev** 2024-12-01 06:57 UTC
Labels: bug
