### ISSUE TITLE
Updating Error : matrix_postgres_connection_password even if renamed to devture _postgres_connection_password

### ISSUE THREAD

**Issue by Unsourire** [spantaleev/matrix-docker-ansible-deploy#2378] opened 2023-01-04 20:13 UTC
Hello,
I got an error with updating to the new version with  matrix_postgres_connection_password even if i changed it in the vars.yml file.
At t he bigining as i didn't replace the matrix_postgres to devture_postgres  i had more variable to change, but even changing everything i got the error the password one even if i changed it.

**To Reproduce**
My `vars.yml` file looks like this:

`matrix_domain: smsnt.net
matrix_homeserver_generic_secret_key: '----------------------------'

matrix_ssl_lets_encrypt_support_email: '------------'

devture_postgres_connection_password: '--------'

matrix_synapse_workers_enabled: true
matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_oidc_api_enabled: true

matrix_synapse_configuration_extension_yaml: |
  user_directory:
    enabled: true
    search_all_users: true
  oidc_providers:
    - idp_id: ----------
      discover: false
      issuer: "-----/"
      idp_name: "----------l"
      client_id: "ff-----19"
      client_secret: "----------"
      scopes: ["profile"]
      authorization_endpoint: "------------------"
      token_endpoint: "-----------------"
      userinfo_endpoint: "-----------------"
      user_profile_method: userinfo_endpoint
      skip_verification: true
      allow_existing_users: true
      user_mapping_provider:
        config:
            subject_claim: username
            display_name_template: "{% raw %}{{ user.displayName }}{% endraw %}"
            email_template: "{% raw %}{{ user.username }}{% endraw %}"
            
matrix_synapse_admin_enabled: true

matrix_synapse_enable_registration: true

matrix_synapse_federation_enabled: false

matrix_mailer_sender_address: "---------------"
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "------------"
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: "----------"
matrix_mailer_relay_auth_password: "-----------"

matrix_synapse_registrations_require_3pid:
 - email

matrix_synapse_autocreate_auto_join_rooms: false

matrix_nginx_proxy_base_domain_serving_enabled: true

#postgre backup
devture_postgres_backup_enabled: true
devture_postgres_backup_schedule: "@daily"
devture_postgres_backup_keep_days: 2
devture_postgres_backup_path: "{{ matrix_base_data_path }}/postgres-backup"

devture_postgres_process_extra_arguments: [
  "-c max_connections=1000",
  "-c shared_buffers=2GB",
  "-c effective_cache_size=6GB",
  "-c maintenance_work_mem=512MB",
  "-c checkpoint_completion_target=0.9",
  "-c wal_buffers=16MB",
  "-c default_statistics_target=100",
  "-c random_page_cost=1.1",
  "-c effective_io_concurrency=200",
  "-c work_mem=1048kB",
  "-c min_wal_size=1GB",
  "-c max_wal_size=4GB",
  "-c max_worker_processes=4",
  "-c max_parallel_workers_per_gather=2",
  "-c max_parallel_workers=4",
  "-c max_parallel_maintenance_workers=2",
]
matrix_prometheus_enabled: true
matrix_prometheus_node_exporter_enabled: true
matrix_grafana_enabled: true
matrix_grafana_anonymous_access: false
matrix_grafana_default_admin_user: "------------"
matrix_grafana_default_admin_password: "------"
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: YOUR_SHARED_SECRET_GOES_HERE
matrix_mautrix_signal_enabled: true
`

**Expected behavior**
I wanted to make an update of the application but when i run the command `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all `

i got this error 
`TASK [custom/matrix_playbook_migration : (Deprecation) Catch and report matrix_postgres variables] ******************************************************************************************
fatal: [matrix.smsnt.net]: FAILED! => changed=false
  msg: |-
    The matrix-postgres role in the playbook has been replaced with the com.devture.ansible.role.postgres role (https://github.com/devture/com.devture.ansible.role.postgres).
    The new role is pretty much the same, but uses differently named variables.

    The matrix-postgres-backup role in the playbook has been replaced with the com.devture.ansible.role.postgres_backup role (https://github.com/devture/com.devture.ansible.role.postgres_backup).
    The new role is pretty much the same, but uses differently named variables.

    Please change your configuration (vars.yml) to rename all `matrix_postgres`-prefixed variables (`matrix_postgres_*` -> `devture_postgres_*`).

    The following variables in your configuration need to be renamed: matrix_postgres_connection_password`

But i have renamed all the variables.

**Matrix Server:**
 - OS:  Ubuntu 21.04
 - Architecture arm64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- I run Ansible on the Matrix server itself with docker `docker run -it --rm \
--privileged \
--pid=host \
-w /work \
-v `pwd`:/work \
--entrypoint=/bin/sh \
docker.io/devture/ansible:2.13.6-r0-1
`

**Comment by QEDeD** [comment] 2023-01-28 22:48
I'm having this issue as well.

I get the error

```
[WARNING]: an unexpected error occurred during Jinja2 environment setup: cannot import name 'environmentfilter' from 'jinja2.filters' (/home/kristoffer/.local/lib/python3.10/site-packages/jinja2/filters.py)   line 0
fatal: [matrix.thewrt.com]: FAILED! => 
  msg: |-
    The conditional check 'vars | dict2items | selectattr('key', 'match', 'matrix_postgres_.*') | list | items2dict' failed. The error was: template error while templating string: cannot import name 'environmentfilter' from 'jinja2.filters' (/home/kristoffer/.local/lib/python3.10/site-packages/jinja2/filters.py)
      line 0. String: {% if vars | dict2items | selectattr('key', 'match', 'matrix_postgres_.*') | list | items2dict %} True {% else %} False {% endif %}
  
    The error appears to be in '/home/kristoffer/git-stuff/matrix-docker-ansible-deploy/roles/custom/matrix_playbook_migration/tasks/validate_config.yml': line 39, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: (Deprecation) Catch and report matrix_postgres variables
      ^ here

```
But I only have one Postgres variable and it is named correctly:

![image](https://user-images.githubusercontent.com/16562457/215294593-c0af7a10-4413-42ce-ac35-62120f39a5b5.png)

**Comment by spantaleev** [comment] 2023-01-29 06:07
@QEDeD, the error message clearly reports that **the problem is with some Jinja2 filter** (*while processing a validation check related to matrix-postgres*).

Try upgrading your Jinja and Ansible versions.

----

@Unsourire, try grepping for `matrix_postgres`. There may be leftover files somewhere. Do you have any other YAML files in the same directory as your vars.yml?

**Comment by QEDeD** [comment] 2023-01-29 18:37
Thanks, @spantaleev.

It sure wasn't clear to me, that the error was related to ansible, but I'm happy it was to you.

I was using Ansible 2.10.7, which was the newest in the PopOS repository, but by adding the Ansible PPA (for details see: https://docs.ansible.com/ansible/latest/installation_guide/installation_distros.html#installing-ansible-on-ubuntu) I got version 2.13 and things started working again.

**Comment by luixxiul** [comment] 2024-11-02 16:50
Closing as resolved.

**Closed by luixxiul** 2024-11-02 16:50 UTC
Labels: question
